CREATE SEQUENCE bsw_personas_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE BSW_PERSONAS (
    ID_PERSONA      NUMBER PRIMARY KEY,
    COD_PERSONA     VARCHAR2(30 CHAR) NOT NULL,
    NOMBRE          VARCHAR2(150 CHAR) NOT NULL,
    RUC             VARCHAR2(20 CHAR),
    DIRECCION       VARCHAR2(250 CHAR),
    TELEFONO        VARCHAR2(50 CHAR),
    FEC_NACIMIENTO  DATE,
    ES_FISICA       CHAR(1) DEFAULT 'S' NOT NULL,
    ES_CLIENTE      CHAR(1) DEFAULT 'N' NOT NULL,
    ES_PROVEEDOR    CHAR(1) DEFAULT 'N' NOT NULL,
    ES_EMPLEADO     CHAR(1) DEFAULT 'N' NOT NULL,
    ESTADO          CHAR(1) DEFAULT 'A' NOT NULL
);

CREATE UNIQUE INDEX UK_BSW_PERSONAS_COD ON BSW_PERSONAS (COD_PERSONA);
